name: freetds
builder:
  name: AutotoolsBuilder
  configure_options: "--with-gnu-ld --with-tdsver=7.1 --disable-odbc --enable-sybase-compat --enable-shared --disable-apps --disable-pool --disable-server"
  environments:
    NOCONFIGURE: "1"
platforms:
  - aix-6.1/powerpc
  - linux-glibc2.11/amd64
