name: freetds
builder:
  name: AutotoolsBuilder
  configure_options: "--with-gnu-ld --with-tdsver=7.1 --disable-odbc --enable-sybase-compat --enable-shared --disable-apps --disable-pool --disable-server"
  environments:
    NOCONFIGURE: "1"
platforms:
  - aix-6.1/powerpc
  - hpux-11v2/ia64
  - solaris-10/amd64
  - solaris-10/sparc
  - solaris-10/sparc64
  - linux-glibc2.3.6/amd64
  - linux-glibc2.3.6/i386
  - linux-glibc2.11/amd64
  - linux-glibc2.11/i386
  - solaris-11/amd64
  - solaris-11/sparc64
  - freebsd-9.2/i386
  - freebsd-9.2/amd64
  - freebsd-10.1/amd64
  - ubuntu-bionic/amd64
